#ifndef __OTYPES_H__
#define __OTYPES_H__

#define TYPE_PLAYER			 1
#define TYPE_SCIENTIST			 2
#define TYPE_SOLDIER    		 3
#define TYPE_POWERUP_ENERGY    		 4
#define TYPE_BOSS_SCIENTIST		 5
#define TYPE_BOSS_SOLDIER		 6
#define TYPE_MINE			 7
#define TYPE_SOLDIER2    		 8
#define TYPE_VAKTM			 9
#define TYPE_WEAPON_FLAME_THROWER 	10
#define TYPE_FLOORGUN			11
#define TYPE_AMMO_FLAME_THROWER 	12
#define TYPE_WEAPON_ICEMAKER	 	13
#define TYPE_AMMO_ICEMAKER	  	14
#define TYPE_WEAPON_GRENADE_LAUNCHER 	15
#define TYPE_AMMO_GRENADE_LAUNCHER 	16
#define TYPE_AMMO_GRENADE_LAUNCHER6 	17
#define TYPE_RAMBO			18
#define TYPE_BOSS_RAMBO			19
#define TYPE_ARNOLD			20
#define TYPE_BOSS_ARNOLD		21
#define TYPE_CHECKPOINT			22
#define TYPE_EXTRA_LIFE			23
#define TYPE_DOOR			24
#define TYPE_BARREL			25
#define TYPE_DOLPH			26
#define TYPE_BOSS_DOLPH			27
#define TYPE_RED_DOOR			28
#define TYPE_BLUE_DOOR			29
#define TYPE_GREEN_DOOR			30
#define TYPE_EINSTEIN			31
#define TYPE_BOSS_EINSTEIN		32
#define TYPE_CRYCHECK			33
#define TYPE_BOSS_CRYCHECK		34
#define TYPE_LEFT_COMPUTER_SCREEN	35
#define TYPE_RIGHT_COMPUTER_SCREEN	36
#define TYPE_RED_CARD			37
#define TYPE_BLUE_CARD			38
#define TYPE_GREEN_CARD			39
#define TYPE_DR_GREEN			40
#define TYPE_BOSS_DR_GREEN		41
#define TYPE_DEKOR_ROBOT1		42
#define TYPE_DEKOR_ROBOT2		43
#define TYPE_DEKOR_ROBOT3		44
#define TYPE_DEKOR_STOL1		45
#define TYPE_DEKOR_STOL2		46
#define TYPE_DEKOR_RITNING1		47
#define TYPE_DEKOR_RITNING2		48
#define TYPE_DEKOR_WEAPON1		49
#define TYPE_DEKOR_HELMET1		50
#define TYPE_DEKOR_ROCKETPART1		51
#define TYPE_DEKOR_ROCKETPART2		52
#define TYPE_DEKOR_ROCKETPART3		53
#define TYPE_AMMO_PLASMA                54
#define TYPE_WEAPON_PLASMA		55
#define TYPE_SEAGAL			56
#define TYPE_BOSS_SEAGAL		57
#define TYPE_DEKOR_FLAG			58
#define TYPE_DOOR_EXTRA_LEVEL		59
#define TYPE_ELEVATOR			60
#define TYPE_ELEVATORSTATION		61

#define TYPE_ELEVUP			62
#define TYPE_ELEVDOWN			63
#define TYPE_ELEVLEFT			64
#define TYPE_ELEVRIGHT			65
#define TYPE_ELEVUP_GREEN		66
#define TYPE_ELEVDOWN_GREEN		67
#define TYPE_ELEVLEFT_GREEN		68
#define TYPE_ELEVRIGHT_GREEN		69
#define TYPE_ELEVUP_RED			70
#define TYPE_ELEVDOWN_RED		71
#define TYPE_ELEVLEFT_RED		72
#define TYPE_ELEVRIGHT_RED		73
#define TYPE_ELEVUP_BLUE		74
#define TYPE_ELEVDOWN_BLUE		75
#define TYPE_ELEVLEFT_BLUE		76
#define TYPE_ELEVRIGHT_BLUE		77
#define TYPE_ELEVWIRE			78

#define TYPE_SOLDIER4			79
#define TYPE_SOLDIER3			80
#define TYPE_WATER			81
#define TYPE_BUBBLEMAKER		82

#define TYPE_AMMO_MINIGUN               83
#define TYPE_WEAPON_MINIGUN		84

#define TYPE_AIRSTRIKER			85

#define TYPE_AMMO_ELECTRIC		86
#define TYPE_WEAPON_ELECTRIC		87

#define TYPE_TANK			88

#endif
